version: '3'
services:
  sentry:
    container_name: sentry
    image: sentry
    env_file:
      - .env
    ports:
      - '9000:9000'

    environment:
      SENTRY_EMAIL_HOST: smtp.gmail.com
      SENTRY_EMAIL_PORT: 587
      SENTRY_EMAIL_USER: 
      SENTRY_EMAIL_PASSWORD: 
      SENTRY_SERVER_EMAIL: 
      SENTRY_EMAIL_USE_TLS: true
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true

    
  cron:
    container_name: sentry-cron
    image: sentry
    command: run cron
    env_file:
      - .env
    depends_on:
      - db
      - redis

      
  worker:
    container_name: sentry-worker
    image: sentry
    command: run worker
    env_file:
      - .env
    depends_on:
      - db
      - redis

      
  redis:
    container_name: sentry-redis
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

      
  db:
    container_name: sentry-postgres
    image: postgres
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: secret
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

      
volumes:
  redis-data:
  pg-data:
